image: rocker/verse:3.5.3


before_script:
  - apt-get update
  - apt-get install build-essential chrpath libssl-dev libxft-dev
  - apt-get install libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /usr/local/share/
  - ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
  - Rscript .gitlab-ci.R

pages:
  stage: deploy
  script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'all', output_dir = 'public')"
  artifacts:
    paths:
    - public
  only:
  - master
