image: rocker/verse:3.5.3


before_script:
  - apt-get update
  - apt-get  -y install bzip2
  - apt-get  -y install r-cran-dt r-cran-readr r-cran-dplyr r-cran-webshot
  - Rscript .gitlab-ci.R

pages:
  stage: deploy
  script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'all', output_dir = 'public')"
  artifacts:
    paths:
    - public
  only:
  - master
