image: rocker/verse:3.5.3


before_script:
  - apt-get update
  - apt-get  -y install bzip2
  - Rscript .gitlab-ci.R

pages:
  stage: deploy
  script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook', output_dir = 'public')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book', output_dir = 'public')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book', output_dir = 'public')"
  artifacts:
    paths:
    - public
  only:
  - master
