image: rocker/verse:3.5.3

variables:
  CHROMOTE_CHROME: "/usr/bin/chromium"
  
before_script:
  - apt-get update
  - apt-get -y install bzip2
  - apt-get -y install chromium chromium-l10n # for webshot
  - Rscript scripts/gitlab-ci.R

pages:
  stage: deploy
  script:
  - Rscript -e "bookdown::render_book('index.Rmd', c('bookdown::gitbook', 'bookdown::pdf_book', 'bookdown::epub_book'))"
  artifacts:
    paths:
    - public
  only:
  - master
