name: Render and Deploy RMarkdown Website
'on': push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install apt dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y --no-install-recommends bzip2 chromium-browser chromium-browser-l10n libgit2-dev
      - name: Install Package Dependencies
        run: |-
          Rscript -e 'install.packages(c("tidyverse", "bookdown", "knitr", "DT", "kableExtra", "tikzDevice", "webshot", "fastmap", "miniCRAN", "igraph", "magrittr", "networkD3", "visNetwork", "fastmap", "devtools", "remotes", "googlesheets"))'
          Rscript -e 'devtoools::install_github(c("rstudio/websocket", "rstudio/webshot2", "r-lib/later", "rstudio/promises"))'
      - run: |-
          Rscript -e "deploy_path <- rmarkdown::render_site(encoding = 'UTF-8')"
          Rscript -e "Sys.setenv(DEPLOY_PATH = deploy_path)"
    container: rocker/verse:latest
